### PR TITLE
Improved Project Documentation 

### PR DESCRIPTION
**Pull request by KanwalpreetSingh1823**
Related Issue (#24)

 Improved Readme.md and Created ContributionGuide.md

### CODE REVIEW

**Comment by Sahil-Gupta584** [comment]
@KanwalpreetSingh1823 Can you please provide preview images

**Comment by KanwalpreetSingh1823** [comment]
You can check it here : 

1. Readme.md : https://github.com/KanwalpreetSingh1823/BooksMall/blob/newFeature/README.md

2. ContributionGuide.md : https://github.com/KanwalpreetSingh1823/BooksMall/blob/newFeature/ContributionGuide.md

**Comment by KanwalpreetSingh1823** [comment]
If you want changes then I will modify it.

**Comment by Sahil-Gupta584** [comment]
Great work @KanwalpreetSingh1823

**Pull request merged**
