### PR TITLE
Added Docker Support and Updated README

### PR DESCRIPTION
**Pull request by mayank-0407**
**Docker Integration:** Added a Dockerfile to the project, enabling the application to run inside a Docker container.

**Updated README:** Updated the README.md to include instructions on how to build and run the Docker container.

**New instructions include:**

- Building the Docker image.
- Running the Docker container.

### CODE REVIEW

**Comment by mayank-0407** [comment]
PR for Issue #42

**Comment by mayank-0407** [comment]
@Sahil-Gupta584 Can you review please review the PR.

**Comment by Sahil-Gupta584** [comment]
well done @mayank-0407 !

**Comment by mayank-0407** [comment]
@Sahil-Gupta584 it is counted as hacktoberfest. Here is ss attached1
Screenshot 2024-10-28 at 5 06 27 PM

**Pull request merged**
