### PR TITLE
fixed bug in the login and signUp pages

### PR DESCRIPTION
**Pull request by agnijeetsharma**
I have fixed the signIn and SignUp pages bugs .
@Sahil-Gupta584 Kindly Merge my PR under hacktoberfest-2024

Fixed pages Video

https://github.com/user-attachments/assets/bc768658-484b-4e66-9882-57b09145038f

### CODE REVIEW

**Comment by Sahil-Gupta584** [comment]
Nice work @agnijeetsharma!

**Comment by agnijeetsharma** [comment]
@Sahil-Gupta584 ,I noticed that my pull request was recently closed. Could you please provide some feedback on what went wrong or why it wasn't merged? As i raised the issue and you assigned me. I'd like to understand the issues so I can improve the contribution or make necessary adjustments for future submissions.

Kindly merge it if it useful and label as hacktoberfest-2024

**Comment by Sahil-Gupta584** [comment]
@agnijeetsharma I have merged your pr but commit giving me conflicts for package-lock.json file there fore it didn't clean automatically did you modified that file? You pr is been merged try to check in hactoberfests dashboard

**Comment by agnijeetsharma** [comment]
Bug is not resolved and as Pr is not merged so it is not showing in the dashboard.
Sir i will again sending PR and i am sure that it would not consist conflicts.
Kindly merge that.
Thanks

**Pull request closed without merging**
